### ISSUE TITLE
ClassLoader is jdk.internal.loader.ClassLoaders$AppClassLoader@4b85612c, not a URLClassLoader

### ISSUE THREAD

**Issue by vitoresende** [bazelbuild/rules_appengine#117]
I followed all the instructions in the README.

My BUILD conf is:

```
load("@io_bazel_rules_appengine//appengine:java_appengine.bzl", "appengine_war")

java_library(
    name = "mylib",
    srcs = ["java/my/webapp/ServletConfig.java", "java/my/webapp/MyServlet.java"],
    deps = [
        "@maven//:com_google_inject_extensions_guice_servlet",
        "@maven//:com_google_inject_guice",
        "@maven//:javax_inject_javax_inject",
        "@maven//:javax_servlet_javax_servlet_api"
    ],
)

appengine_war(
    name = "myapp",
    jars = [":mylib"],
    data = glob(["java/**"]),
    data_path = "/",
)
```

The command bazelbuild build works perfectly but when I run **bazel run //app_engine:myapp** I get the following error:
```
INFO: Analyzed target //app_engine:myapp (1 packages loaded, 4 targets configured).
INFO: Found 1 target...
Target //app_engine:myapp up-to-date:
  bazel-bin/app_engine/myapp.war
  bazel-bin/app_engine/myapp_deploy.sh
  bazel-bin/app_engine/myapp
INFO: Elapsed time: 0.250s, Critical Path: 0.02s
INFO: 3 processes: 3 internal.
INFO: Build completed successfully, 3 total actions
INFO: Build completed successfully, 3 total actions
java.lang.RuntimeException: Unable to create a DevAppServer
	at com.google.appengine.tools.development.DevAppServerFactory.doCreateDevAppServer(DevAppServerFactory.java:401)
	at com.google.appengine.tools.development.DevAppServerFactory.access$000(DevAppServerFactory.java:31)
	at com.google.appengine.tools.development.DevAppServerFactory$1.run(DevAppServerFactory.java:318)
	at com.google.appengine.tools.development.DevAppServerFactory$1.run(DevAppServerFactory.java:315)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.google.appengine.tools.development.DevAppServerFactory.createDevAppServer(DevAppServerFactory.java:314)
	at com.google.appengine.tools.development.DevAppServerMain$StartAction.apply(DevAppServerMain.java:374)
	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:45)
	at com.google.appengine.tools.development.DevAppServerMain.run(DevAppServerMain.java:247)
	at com.google.appengine.tools.development.DevAppServerMain.main(DevAppServerMain.java:238)
Caused by: java.lang.ClassCastException: ClassLoader is jdk.internal.loader.ClassLoaders$AppClassLoader@4b85612c, not a URLClassLoader.
	at com.google.apphosting.utils.security.SecurityManagerInstaller.generatePolicyFile(SecurityManagerInstaller.java:139)
	at com.google.apphosting.utils.security.SecurityManagerInstaller.install(SecurityManagerInstaller.java:94)
	at com.google.appengine.tools.development.DevAppServerFactory.doCreateDevAppServer(DevAppServerFactory.java:377)
	... 9 more
```

**Comment by pmbethe09** [comment]
Can you provide platform information? OS and version?
