### ISSUE TITLE
Bazel incompatible changes

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/rules_appengine#97]
Based on our latest CI run (https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/28#7292f5b2-bd4a-4183-9ed8-819c84282ee6), migration is needed for the following flags:
  * --incompatible_depset_is_not_iterable
  * --incompatible_depset_union
  * --incompatible_disallow_legacy_py_provider
  * --incompatible_new_actions_api

Can you please take a look and report any problem with it?

**Comment by pmbethe09** [comment]
that fails
ERROR: /usr/local/google/home/pbethe/golang/src/github.com/bazelbuild/rules_appengine/test/java/BUILD:3:1: in appengine_war_base rule //test/java:test-war: 
Traceback (most recent call last):
	File "/usr/local/google/home/pbethe/golang/src/github.com/bazelbuild/rules_appengine/test/java/BUILD", line 3
		appengine_war_base(name = 'test-war')
	File "/usr/local/google/home/pbethe/golang/src/github.com/bazelbuild/rules_appengine/appengine/java_appengine.bzl", line 150, in _war_impl
		_collect_transitive_runtime_deps_for(ctxt.attr.jars)
	File "/usr/local/google/home/pbethe/golang/src/github.com/bazelbuild/rules_appengine/appengine/java_appengine.bzl", line 121, in _collect_transitive_runtime_deps_for
		transitive_runtime_deps += dep.files
`+` operator on a depset is forbidden. See https://docs.bazel.build/versions/master/skylark/depsets.html for recommendations. Use --incompatible_depset_union=false to temporarily disable this check.
ERROR: Analysis of target '//test/java:test-war' failed; build aborted: Analysis of target '//test/java:test-war' failed; build aborted

**Comment by pmbethe09** [comment]
@laurentlb how do you fix depset += ?

**Comment by laurentlb** [comment]
General documentation: https://docs.bazel.build/versions/master/skylark/depsets.html
More specifically, see Hanwen's comment and mine: https://github.com/bazelbuild/bazel/issues/5817#issuecomment-452699500

**Comment by pmbethe09** [comment]
OK -- I have the java rules working, but the py rules trip on --incompatible_disallow_legacy_py_provider

**Comment by laurentlb** [comment]
`incompatible_disallow_legacy_py_provider` is pretty new. You can comment on https://github.com/bazelbuild/bazel/issues/7298 for advice.
If you fixed the other issues, that's already a nice improvement.

**Comment by brandjon** [comment]
I mailed #99 for `--incompatible_disallow_legacy_py_provider` (before I saw this thread).

**Comment by fejta** [comment]
Can we get a new tag? 0.0.8 is the latest and uses a bunch of unsupported bazel functionality

**Comment by pmbethe09** [comment]
Should we tag as-is, or make changes to appengine/BUILD to deal with the toolchain related warnings?

**Comment by fejta** [comment]
fdbce051adecbb369b15260046f4f23684369efc seems to work with bazel 0.24.0

https://github.com/kubernetes/test-infra/blob/098e7f1727229bcc2602ae5f5f99a646e9bb5217/WORKSPACE#L476-L482

**Comment by pmbethe09** [comment]
Done.  0.0.9 created from head
